version: 2

models:
   - name: stg_customers
     description : one unique customer per data
     columns:
        - name: customer_id
          description : primary key for the customer table
          tests:
            - unique
            - not_null
   - name: stg_orders
     columns:
        - name: status
          description : '{{doc("order_status")}}'
          tests:
            - accepted_values:
                values: ['completed','shipped','returned','placed','return_pending']
        - name: customer_id
          tests:
            - relationships:
                to: ref('stg_customers')
                field: customer_id